Code syntax highlighting
keombre/progtest-theme pull request #11
Opened 2019-10-19 14:59 UTC by Darxeal

This adds code syntax highlighting using the [highlight.js](https://highlightjs.org/) library. It automatically detects the language. I added styles for both Light and Dark themes. Some examples:

![image](https://user-images.githubusercontent.com/18472149/67146953-a80ac000-f290-11e9-826e-259daba46e70.png)

![image](https://user-images.githubusercontent.com/18472149/67146963-c53f8e80-f290-11e9-86a7-6194713389c1.png)

I made it a part of the `Logged` class, so it works in pages like FAQ and exams:

![image](https://user-images.githubusercontent.com/18472149/67146995-f4ee9680-f290-11e9-8686-d4d511e8ca28.png)

2019-10-19 18:39 UTC, keombre commented
Great work!

Just couple of small issues:
- Licence should be updated to include BSD 3-Clause License with reference to `hightlight.js`,
- I'm not sure if text from help boxes in task solution should be highlighted as well.

Other than that it looks like it's merge ready 👍

2019-10-19 19:41 UTC, keombre requested changes
Add a copy of `highlight.js` licence

2019-10-19 19:41 UTC, keombre commented on content/end.js
> +            hljs.highlightBlock(block);
We sboulh format code only if language relevance is above a threshold.
For example:
```js
let formatted = hljs.highlightAuto(block.innerText)
if (formatted.r > 5) block.innerHTML = formatted.value
block.classList.add('hljs')
```

2019-10-20 12:08 UTC, Darxeal commented
I'm not a fan of the relevance solution. For example, it doesn't want to highlight code like `public int function()`, because this is valid in a lot of languages so the relevance is very low.

I suggest another solution - highlight.js let's you download a custom library for only the languages you want. So we could get one that supports only C++ and Java, because those are the only languages taught in progtest, as far as I know. There's also Bash, but that doesn't have very specific syntax rules so I would exclude it. 

That should mean that code blocks that don't support C++ or Java syntax will not get highlighted.

2019-10-20 15:43 UTC, keombre approved these changes

2019-10-20 15:47 UTC, merged